language: node_js
node_js:
  - '12'

script:
  - npm run build
                
deploy:
  provider: script
  script:
    - npx now --prod --confirm --no-clipboard --token=$NOW_TOKEN --public
  skip_cleanup: true
  on:
    branch: master
